app/views/badge.py
import csv
import io
import re

from flask import Blueprint, render_template, flash

from flask_login import current_user, login_required

from app.forms.csv_upload import CSVUploadForm
from app.models import Level, Flag, Badge
from app import db


app = Blueprint('badge', __name__)


@app.route('/upload', methods=['GET', 'POST'])
@login_required
def upload():
    levels = {l.name: l for l in Level.query.all()}
    flags = {f.name: f for f in Flag.query.all()}

    form = CSVUploadForm()
    if form.validate_on_submit():
        with db.session.no_autoflush:
            if form.csv_file.data:
                reader = csv.DictReader(form.csv_file.data.stream, dialect='excel')
            else:
                reader = csv.DictReader(io.StringIO(form.raw_csv.data), delimiter='\t')
            ok = True
            for idx, row in enumerate(reader):
                adj_idx = idx + 2
                for field in ('name', 'level', 'age'):
                    if not row.get(field):
                        flash(f"Row {adj_idx} is missing required field {field}, aborting", 'danger')
                        ok = False
                        break
                if row.get('level') not in levels:
                    flash(f"Row {adj_idx} has an invalid level, aborting", 'danger')
                    ok = False
                    break
                if row.get('flags'):
                    row['flags'] = re.split(r'\s+', row['flags'])
                    for flag in row['flags']:
                        if flag not in flags:
                            flash(f"Row {adj_idx} has an invalid flag, aborting", 'danger')
                            ok = False
                            break

                if not ok:
                    break

                row['level'] = levels[row['level']]
                row['flags'] = [flags[f] for f in row['flags']] if row.get('flags') else []
                row['age'] = int(row['age'])
                badge = Badge(**row)

                if form.queue.data:
                    badge.print_queued = True
                    badge.print_queued_by = current_user

                db.session.add(badge)

            if ok:
                db.session.commit()
                flash("Uploaded {} records".format(idx + 1), 'success')
                form.csv_file.data = None
                form.raw_csv.data = None
            else:
                db.session.rollback()

    valid_levels = ', '.join(levels.keys())
    valid_flags = ', '.join(flags.keys())
    return render_template('badge/upload.jinja.html', form=form, valid_levels=valid_levels, valid_flags=valid_flags)


@app.route('/list', methods=['GET'])
def list():
    badges = Badge.query
    return render_template('badge/list.jinja.html', badges=badges)

app/views/index.py
import mimetypes
import os

from flask import (
    Blueprint,
    url_for,
    render_template,
    redirect,
    flash,
    current_app,
    Response,
    request,
    )
from flask_login import current_user, login_required

from app.models import Badge, BadgeTemplate, BadgePrint
from app import db


app = Blueprint('index', __name__)
mimetypes.init()


def match_templates(single=False):
    templates = BadgeTemplate.query.all()
    badges = Badge.query.filter(Badge.print_queued == True).all()
    badge_templates = {}
    for badge in badges:
        tpl_match = [(t, t.matches(badge)) for t in templates]
        if tpl_match:
            tpl_match = list(sorted(tpl_match, key=lambda v: v[1]))
            tpl_match = [v[0] for v in tpl_match if v[1] > 0 and v[1] == tpl_match[-1][1]]
        badge_templates[badge.id] = tpl_match[-1] if single else tpl_match
    return badges, badge_templates


def group_count(data, n):
    out = []
    for v in data:
        out.append(v)
        if len(out) == n:
            yield out
            out = []
    if out:
        yield out


@app.route('/', methods=['GET'])
@login_required
def index():
    root_templates = BadgeTemplate.query.filter(BadgeTemplate.extends == None).all()
    badges, badge_templates = match_templates()
    return render_template('index.jinja.html', root_templates=root_templates, badges=badges, badge_templates=badge_templates)


@app.route('/queue', methods=['POST'])
@login_required
def queue():
    if request.form.get('action') == 'queue-unprinted':
        unprinted = [b for b in Badge.query if not b.print_queued and not b.prints]
        for b in unprinted:
            b.print_queued = True
            b.print_queued_by = current_user
        db.session.commit()
        flash("Queued {} badges for printing".format(len(unprinted)), 'success')
    elif request.form.get('action') == 'queue-all':
        unprinted = [b for b in Badge.query if not b.print_queued]
        for b in unprinted:
            b.print_queued = True
            b.print_queued_by = current_user
        db.session.commit()
        flash("Queued {} badges for printing".format(len(unprinted)), 'success')
    elif request.form.get('action') == 'queue':
        badge = Badge.query.filter(Badge.print_queued == False, Badge.id == request.form.get('id')).first()
        if badge:
            badge.print_queued = True
            badge.print_queued_by = current_user
            db.session.commit()
            flash("Queued {} for printing".format(badge.name), 'success')
        else:
            flash("No such badge", 'danger')
    elif request.form.get('action') == 'unqueue':
        badges = Badge.query.filter(Badge.print_queued == True)
        if request.form.get('id'):
            badges = badges.filter(Badge.id == request.form.get('id'))
        badges = badges.all()

        for b in badges:
            b.print_queued = False
            b.print_queued_by = None

        db.session.commit()
        flash("Unqueued {} badges".format(len(badges)), 'success')
    else:
        flash("Invalid action", 'danger')

    return redirect(request.form.get('next') or url_for('.index'))


@app.route('/print', methods=['GET'])
@login_required
def print():
    root_templates = BadgeTemplate.query.filter(BadgeTemplate.extends == None).all()
    if request.args.get('tpl'):
        badge_templates = {0: BadgeTemplate.query.get(request.args['tpl'])}
        badges = [
            {
                'id': 0,
                'name': '',
                'level': '',
            }
            for _ in range(int(request.args['count']))
        ]
    else:
        badges, badge_templates = match_templates(single=True)
        for b in badges:
            db.session.add(BadgePrint(
                badge=b,
                queued_by=b.print_queued_by,
                printed_by=current_user,
            ))
        db.session.commit()
    badges = list(group_count(badges, 6))
    badges = list(map(lambda g: list(group_count(g, 3)), badges))
    return render_template('badge/print.jinja.html', root_templates=root_templates, badges=badges, badge_templates=badge_templates)


@app.route('/uploads/<path:filename>', methods=['GET'])
def upload(filename):
    mime, _ = mimetypes.guess_type(os.path.basename(filename), strict=False)
    with open(os.path.join(current_app.config['UPLOAD_PATH'], filename), 'rb') as fp:
        content = fp.read()
    return Response(content, mimetype=mime)

app/views/user.py
from flask import (
    Blueprint,
    url_for,
    render_template,
    flash,
    redirect,
    )
from flask_login import login_user, logout_user, current_user

from app.forms.user import (
    LoginForm,
    )

from app.models import User

app = Blueprint('user', __name__)


@app.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()

    if form.validate_on_submit():
        if form.submit_login.data:
            user = User.query.filter(User.username.like(form.username.data)).first()
            if user and user.password == form.password.data:
                login_user(user, remember=True if form.remember_me.data else False)
                return redirect(url_for('index.index'))
            else:
                flash("Invalid username or password", 'danger')
        else:
            flash("No action", 'danger')

    return render_template('user/login.jinja.html', form=form)


@app.route('/logout', methods=['GET'])
def logout():
    logout_user()
    return redirect(url_for('index.index'))

app/templates/base-fullscreen.jinja.html
{% extends "root.jinja.html" %}

app/templates/base.jinja.html
{% extends "root.jinja.html" %}

{% block navbar %}
<nav class="navbar main-nav navbar-fixed-top navbar-inverse">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-nav" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <!-- <a class="navbar-brand" href="{{ url_for('index.index') }}">{{ config.get('SITE_NAME') }}</a> -->
            <a class="navbar-brand" href="/">{{ title if title is defined else config.get('SITE_NAME') }}</span>
        </div>

        <div class="collapse navbar-collapse" id="main-nav">
            <!-- Collect the nav links, forms, and other content for toggling -->
            <ul class="nav navbar-nav navbar-left">
                <li>
                    <a href="{{ url_for('badge.upload') }}">Upload Badges</a>
                </li>
                <li>
                    <a href="{{ url_for('badge.list') }}">List Badges</a>
                </li>
            </ul>
            {#
            <ul class="nav navbar-nav navbar-left">
                <li><a href="{{ url_for('index.index') }}">
                    <i class="fa fa-home"></i>&nbsp;
                    {%- if current_user.is_authenticated -%}
                        Dashboard
                    {%- else -%}
                        Home
                    {%- endif -%}
                </a></li>
                {% for page in config.THEME_PAGES -%}
                    {% if 'nav_order' in page and page.title -%}
                        <li><a href="{{ url_for(page.endpoint) }}">
                            <i class="fa fa-{{ page.fa_icon or 'file' }}"></i>
                            {{ page.title }}
                        </a></li>
                    {%- endif %}
                {%- endfor %}
            </ul>
            #}
            <ul class="nav navbar-nav navbar-right">
                {%- if current_user.is_authenticated -%}
                    {# TODO: check whether user has admin rights #}
                    <li><a href="{{ url_for('admin.index') }}"><i class="fa fa-cog"></i> Administration</a></li>
                    <li><a href="{{ url_for('user.logout') }}"><i class="fa fa-sign-out-alt"></i> Log Out</a></li>
                {%- else -%}
                    <li><a href="{{ url_for('user.login') }}"><i class="fa fa-sign-in-alt"></i> Log In</a></li>
                {%- endif -%}
            </ul>
        </div>
    </div><!-- /.container-fluid -->
</nav>
{% endblock %}

app/templates/flask_admin_base.jinja.html
{% extends "admin/base.html" %}

{% block head %}
    {{ super() }}
{% endblock %}

app/templates/index.jinja.html
{% extends "base.jinja.html" %}
{% from "bootstrap/utils.html" import flashed_messages %}
{% import "bootstrap/wtf.html" as wtf %}

{% macro render_tpl_list(tpl_list) %}
    {% if tpl_list |length %}
        <ul class="media-list">
            {% for tpl in tpl_list %}
                <li class="media">
                    <div class="media-left">
                        <a href="#">
                            <img class="media-object" src="{{ tpl.image_url or url_for('static', filename='img/blank-badge.jpg') }}" alt="">
                        </a>
                    </div>
                    <div class="media-body">
                        <div>
                            <h4 class="media-heading">{{ tpl.name }}</h4>
                            <p>{{ tpl.description }}</p>
                            <div>
                                <button class="btn btn-xs btn-info print-many" data-tpl-id="{{ tpl.id }}">
                                    <i class="fa fa-print"></i>
                                    Print Many
                                </button>
                            </div>
                        </div>
                        {{ render_tpl_list(tpl.extended_by) }}
                    </div>
                </li>
            {% endfor %}
        </ul>
    {% endif %}
{% endmacro %}

{% block content %}
    {{ super() }}
    <div class="row-fluid">
        <div class="col-sm-6 badge-template-list">
            {{ render_tpl_list(root_templates) }}
        </div>
        <div class="col-sm-6">
            <div class="panel panel-default">
                <!-- Default panel contents -->
                <div class="panel-heading">Print Queue</div>
                <div class="panel-body">
                    <form method="POST" action="{{ url_for('index.queue') }}">
                        <a class="btn btn-xs btn-info" href="{{ url_for('index.print') }}" target="_blank" id="print-queue">
                            <i class="fa fa-print"></i>
                            Print
                        </a>
                        <button class="btn btn-xs btn-primary" type="submit" name="action" value="queue-unprinted">
                            <i class="fa fa-plus"></i>
                            Queue Unprinted
                        </button>
                        <button class="btn btn-xs btn-warning" type="submit" name="action" value="queue-all">
                            <i class="fa fa-asterisk"></i>
                            Queue All
                        </button>
                        <button class="btn btn-xs btn-danger" type="submit" name="action" value="unqueue" id="clear-queue">
                            <i class="fa fa-trash"></i>
                            Clear Queue
                        </button>
                    </form>
                </div>

                <table class="table table-striped">
                    <tr>
                        <th>Name</th>
                        <th>Template</th>
                        <th>&nbsp;</th>
                    </tr>
                    {% for badge in badges %}
                        <tr>
                            <td>{{ badge.name }}</td>
                            <td>
                                {% if badge_templates[badge.id] |length == 0 %}
                                    <span class="label label-danger">No Matching Template</span>
                                {% else %}
                                    {% if badge_templates[badge.id] |length > 1 %}
                                        <span class="label label-danger">Multiple Matches</span>
                                    {% endif %}
                                    {% for tpl in badge_templates[badge.id] %}
                                        {{ tpl.name }}{{ ', ' if not loop.last }}
                                    {% endfor %}
                                {% endif %}
                            </td>
                            <td>
                                <form method="POST" action="{{ url_for('index.queue') }}">
                                    <input type="hidden" name="id" value="{{ badge.id }}" />
                                    <button class="btn btn-xs btn-danger" type="submit" name="action" value="unqueue">
                                        <i class="fa fa-trash"></i>
                                        Unqueue
                                    </button>
                                </form>
                            </td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script>
        $('.print-many').on('click', function(e) {
            var tpl_id = $(e.currentTarget).attr('data-tpl-id');
            var count = prompt("Print how many?");
            var win = window.open('/print?tpl=' + tpl_id + '&count=' + count, '_blank');
        });
        $('#print-queue').on('click', function(e) {
            var cb = function() {
                window.removeEventListener('focus', cb);
                if (confirm("Clear print queue?")) {
                    $('#clear-queue').click();
                }
            };
            window.addEventListener('focus', cb);
        });
    </script>
{% endblock %}

app/templates/root.jinja.html
{% extends "bootstrap/base.html" %}
{% from "bootstrap/utils.html" import flashed_messages %}

{% block styles %}
    {{ super() }}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css') }}" />

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/fontawesome-free-5.0.6/web-fonts-with-css/css/fontawesome-all.min.css') }}" />
{% endblock %}

{% block content %}
    {{ flashed_messages() }}
    {{ super() }}
{% endblock %}

{% block scripts %}
    {{ super() }}
{% endblock %}